/* Camada de amplificação v68: especificação executável, exemplares e gates locais. */
(function(S){
  'use strict';
  const palavras=v=>(String(v||'').match(/[\p{L}\p{N}]+(?:[’'-][\p{L}\p{N}]+)*/gu)||[]).length;
  const CLICHES=[/era uma vez/gi,/mal sabia (?:ele|ela)/gi,/desde os prim[oó]rdios/gi,/jornada inesquec[ií]vel/gi,/segredos? (?:há muito )?esquecidos?/gi,/nada seria como antes/gi,/em um mundo onde/gi];
  function compilarSpec(op,ctx){op=op||{};ctx=ctx||{};const c=op.contrato||{},min=Number(c.minPalavras)||0,max=Number(c.maxPalavras)||0,canon=(ctx.termosCanon||[]).slice(0,24);return{minPalavras:min,maxPalavras:max||Math.max(min,0),batidas:(c.secoesObrigatorias||[]).slice(0,12),arquivos:(c.arquivosEsperados||[]).slice(0,12),canon,proibidos:['metatexto interno','placeholders','ações externas fictícias','seções de bíblia/guia dentro do produto'],destino:op.clienteVisivel?'cliente':'interno'};}
  function selecionarExemplar(e,projectId,kit){const itens=[...(e&&e.acervoUsuario||[]),...(e&&e.arquivos||[])].filter(a=>(!projectId||a.projectId===projectId)&&String(a.conteudo||'').length>300&&(a.soberano||a.classe==='produto'||a.validacao&&a.validacao.pronto));const a=itens.find(x=>x.kit===kit)||itens[0];return a?{id:a.id,nome:a.nome,trecho:String(a.conteudo).slice(0,1400)}:null;}
  function perfil(op){const kit=String(op&&op.kit||''),estruturada=op&&op.estruturada;if(estruturada)return{temperature:0.1,top_p:0.8,frequency_penalty:0,seed:68};if(kit==='texto')return{temperature:0.62,top_p:0.92,frequency_penalty:0.12};if(['codigo','pagina','dados','financeiro','laboratorio'].includes(kit))return{temperature:0.2,top_p:0.82,frequency_penalty:0};return{temperature:0.45,top_p:0.9,frequency_penalty:0.05};}
  function repeticaoNgram(texto,n=5){const w=String(texto||'').toLowerCase().match(/[\p{L}\p{N}]+/gu)||[],m=new Map();for(let i=0;i<=w.length-n;i++){const k=w.slice(i,i+n).join(' ');m.set(k,(m.get(k)||0)+1);}return[...m.entries()].filter(([,q])=>q>=3).sort((a,b)=>b[1]-a[1]).slice(0,8);}
  function validar(texto,spec){texto=String(texto||'');spec=spec||{};const total=palavras(texto),notas=[],cliches=CLICHES.reduce((n,rx)=>{rx.lastIndex=0;return n+(texto.match(rx)||[]).length;},0),tokens=texto.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[],diversidade=new Set(tokens).size/Math.max(1,tokens.length),ngrams=repeticaoNgram(texto);if(spec.minPalavras&&total<spec.minPalavras)notas.push(`faltam ${spec.minPalavras-total} palavras para o contrato`);if(spec.maxPalavras&&total>spec.maxPalavras)notas.push(`excede o máximo em ${total-spec.maxPalavras} palavras`);for(const b of spec.batidas||[])if(!texto.toLowerCase().includes(String(b).toLowerCase()))notas.push(`critério ausente: ${b}`);if(total>350&&cliches/total*1000>3)notas.push('densidade de clichês acima do gate');if(total>500&&diversidade<0.22)notas.push('diversidade lexical baixa');if(ngrams.length)notas.push('blocos de linguagem repetidos');return{pronto:notas.length===0,notas:notas.slice(0,12),metricas:{palavras:total,cliches,clichesPorMil:total?cliches/total*1000:0,diversidadeLexical:diversidade,ngramsRepetidos:ngrams.length}};}
  const ferramentas=[
    {type:'function',function:{name:'ler_artefato',description:'Lê um artefato real pelo id, somente leitura.',parameters:{type:'object',properties:{id:{type:'string'},inicio:{type:'integer'},fim:{type:'integer'}},required:['id']}}},
    {type:'function',function:{name:'buscar_canon',description:'Busca um termo no acervo e artefatos do projeto.',parameters:{type:'object',properties:{termo:{type:'string'}},required:['termo']}}},
    {type:'function',function:{name:'contar_palavras',description:'Conta palavras de um texto fornecido.',parameters:{type:'object',properties:{texto:{type:'string'}},required:['texto']}}}
  ];
  function executarFerramenta(nome,args,ctx){args=args||{};const e=ctx&&ctx.empresa||(S.state&&S.state.atual&&S.state.atual());if(nome==='contar_palavras')return{palavras:palavras(args.texto)};if(nome==='ler_artefato'){const a=e&&[...(e.arquivos||[]),...(e.acervoUsuario||[])].find(x=>x.id===args.id);if(!a)return{erro:'artefato inexistente'};const ls=String(a.conteudo||'').split(/\r?\n/),ini=Math.max(1,Number(args.inicio)||1),fim=Math.min(ls.length,Number(args.fim)||ini+120);return{id:a.id,nome:a.nome,inicio:ini,fim,conteudo:ls.slice(ini-1,fim).join('\n')};}if(nome==='buscar_canon'){const termo=String(args.termo||'').toLowerCase();return[...(e&&e.arquivos||[]),...(e&&e.acervoUsuario||[])].filter(a=>String(a.conteudo||'').toLowerCase().includes(termo)).slice(0,8).map(a=>({id:a.id,nome:a.nome}));}return{erro:'ferramenta não autorizada'};}
  function preparar(op,ctx){const e=ctx&&ctx.empresa||(S.state&&S.state.atual&&S.state.atual()),spec=compilarSpec(op,ctx),exemplar=selecionarExemplar(e,op&&op.projectId,op&&op.kit),amostra=exemplar?`\nEXEMPLAR APROVADO (${exemplar.nome}) — imite densidade e precisão, não o conteúdo:\n${exemplar.trecho}`:'';return{spec,exemplar,perfil:perfil(op),prompt:`ESPECIFICAÇÃO EXECUTÁVEL:\n${JSON.stringify(spec)}${amostra}`,tools:ferramentas,executar:(n,a)=>executarFerramenta(n,a,{empresa:e})};}
  async function melhorDeN(gerar,avaliar,n=2){const xs=[];for(let i=0;i<Math.max(1,Math.min(3,n));i++){const valor=await gerar(i);xs.push({valor,nota:Number(await avaliar(valor))||0});}return xs.sort((a,b)=>b.nota-a.nota)[0];}
  S.buff={compilarSpec,selecionarExemplar,perfil,validar,preparar,ferramentas,executarFerramenta,melhorDeN};
})(window.S);
