/* Camada de amplificação v68: especificação executável, exemplares e gates locais. */
(function(S){
  'use strict';
  const palavras=v=>(String(v||'').match(/[\p{L}\p{N}]+(?:[’'-][\p{L}\p{N}]+)*/gu)||[]).length;
  const CLICHES=[/era uma vez/gi,/mal sabia (?:ele|ela)/gi,/desde os prim[oó]rdios/gi,/jornada inesquec[ií]vel/gi,/segredos? (?:há muito )?esquecidos?/gi,/nada seria como antes/gi,/em um mundo onde/gi];
  const SETORES=['criacao','desenvolvimento','producao','operacoes','comercial','financeiro','laboratorio'],DESTINOS=['cliente','interno'],KITS=['autonomo','texto','visual','pagina','codigo','dados','comercial','financeiro','laboratorio'];
  const fichaSchema={type:'object',properties:{nome:{type:'string',minLength:2},setor:{type:'string',enum:SETORES},cargo:{type:'string',minLength:2},tracos:{type:'string'},comunicacao:{type:'string'},prioridades:{type:'string'},estilo:{type:'string'},colaboracao:{type:'string'},aversoes:{type:'string'},experiencia:{type:'string'}},required:['nome','setor','cargo','tracos','comunicacao','prioridades','estilo','colaboracao','aversoes','experiencia'],additionalProperties:false};
  const pecaSchema={type:'object',properties:{titulo:{type:'string',minLength:6},setor:{type:'string',enum:SETORES},destino:{type:'string',enum:DESTINOS},aceite:{type:'array',minItems:1,maxItems:8,items:{type:'string',minLength:2}},min_palavras:{type:'integer',minimum:0,maximum:10000},max_palavras:{type:'integer',minimum:0,maximum:15000},arquivos:{type:'array',maxItems:8,items:{type:'string'}},depende:{type:'array',maxItems:8,items:{type:'string'}},kit:{type:'string',enum:KITS}},required:['titulo','setor','destino','aceite','min_palavras','max_palavras','arquivos','depende','kit'],additionalProperties:false};
  const FUNDACAO_SCHEMA={type:'object',properties:{nome:{type:'string',minLength:2},ramo:{type:'string',minLength:2},tipo_produto:{type:'string',minLength:2},publico:{type:'string',minLength:2},slogan:{type:'string'},missao:{type:'string',minLength:12},visao:{type:'string'},valores:{type:'array',minItems:3,maxItems:5,items:{type:'string'}},posicionamento:{type:'string'},tom:{type:'string'},cores:{type:'string'},tipografia:{type:'string'},estilo_visual:{type:'string'},forma:{type:'string',enum:['serial','pacote','acervo','iterada','servico']},equipe:{type:'array',minItems:3,maxItems:4,uniqueItems:true,items:{type:'string',enum:SETORES}},funcionarios:{type:'array',minItems:3,maxItems:4,items:fichaSchema},plano_negocio:{type:'string',minLength:120},nome_produto:{type:'string',minLength:2},primeiro_produto:{type:'string',minLength:120},manifesto:{type:'string',minLength:40},pecas:{type:'array',minItems:8,maxItems:15,items:pecaSchema}},required:['nome','ramo','tipo_produto','publico','slogan','missao','visao','valores','posicionamento','tom','cores','tipografia','estilo_visual','forma','equipe','funcionarios','plano_negocio','nome_produto','primeiro_produto','manifesto','pecas'],additionalProperties:false};
  function extrairJSON(v){if(v&&typeof v==='object')return v;const t=String(v||'').trim().replace(/^```(?:json)?\s*|\s*```$/gi,'');try{return JSON.parse(t);}catch(_){const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(t.slice(a,b+1));}catch(__){}return null;}}
  function validarFundacao(v){const x=extrairJSON(v),erros=[];if(!x)return{pronto:false,erros:['resposta não é JSON válido'],valor:null,pontuacao:0};const vazio=z=>z==null||(typeof z==='string'&&!z.trim())||(Array.isArray(z)&&!z.length);for(const k of FUNDACAO_SCHEMA.required)if(vazio(x[k]))erros.push(`campo obrigatório ausente ou vazio: ${k}`);if(!['serial','pacote','acervo','iterada','servico'].includes(x.forma))erros.push('forma fora do enum');if(!Array.isArray(x.equipe)||x.equipe.length<3||x.equipe.length>4||new Set(x.equipe).size!==x.equipe.length||x.equipe.some(s=>!SETORES.includes(s)))erros.push('equipe deve conter 3–4 setores válidos e únicos');if(!Array.isArray(x.funcionarios)||x.funcionarios.length<3||x.funcionarios.length>4)erros.push('funcionarios deve conter 3–4 fichas');for(const [i,f] of (x.funcionarios||[]).entries()){if(!f||!SETORES.includes(f.setor))erros.push(`funcionarios[${i}].setor fora do enum`);for(const k of fichaSchema.required)if(vazio(f&&f[k]))erros.push(`funcionarios[${i}].${k} vazio`);}if(!Array.isArray(x.pecas)||x.pecas.length<8||x.pecas.length>15)erros.push('pecas deve conter de 8 a 15 itens');for(const [i,p] of (x.pecas||[]).entries()){for(const k of pecaSchema.required)if(vazio(p&&p[k])&& !['arquivos','depende'].includes(k))erros.push(`pecas[${i}].${k} vazio`);if(!p||String(p.titulo||'').trim().length<6)erros.push(`pecas[${i}].titulo inválido`);if(!SETORES.includes(p&&p.setor))erros.push(`pecas[${i}].setor fora do enum`);if(!DESTINOS.includes(p&&p.destino))erros.push(`pecas[${i}].destino fora do enum`);if(!Array.isArray(p&&p.aceite)||!p.aceite.length||p.aceite.some(vazio))erros.push(`pecas[${i}].aceite vazio`);if(!KITS.includes(p&&p.kit))erros.push(`pecas[${i}].kit fora do enum`);if(!Number.isInteger(p&&p.min_palavras)||!Number.isInteger(p&&p.max_palavras)||Number(p&&p.min_palavras)<0||Number(p&&p.max_palavras)<0)erros.push(`pecas[${i}] tem faixa de palavras inválida`);if(Number(p&&p.max_palavras)>0&&Number(p&&p.min_palavras)>Number(p&&p.max_palavras))erros.push(`pecas[${i}] tem faixa de palavras invertida`);}const clientes=(x.pecas||[]).filter(p=>p&&p.destino==='cliente').length;if(!clientes)erros.push('o plano não possui peça destinada ao cliente');const completos=(x.pecas||[]).filter(p=>p&&p.titulo&&SETORES.includes(p.setor)&&DESTINOS.includes(p.destino)&&Array.isArray(p.aceite)&&p.aceite.length).length,pontuacao=(erros.length?0:1000)+completos*10+clientes*4;return{pronto:erros.length===0,erros:[...new Set(erros)].slice(0,30),valor:x,pontuacao,clientes,completos};}
  function formatoFundacao(){return{type:'json_schema',json_schema:{name:'fundacao_empresa',strict:true,schema:FUNDACAO_SCHEMA}};}
  function compilarSpec(op,ctx){op=op||{};ctx=ctx||{};const c=op.contrato||{},min=Number(c.minPalavras)||0,max=Number(c.maxPalavras)||0,canon=(ctx.termosCanon||[]).slice(0,24);return{minPalavras:min,maxPalavras:max||Math.max(min,0),batidas:(c.secoesObrigatorias||[]).slice(0,12),arquivos:(c.arquivosEsperados||[]).slice(0,12),canon,proibidos:['metatexto interno','placeholders','ações externas fictícias','seções de bíblia/guia dentro do produto'],destino:op.clienteVisivel?'cliente':'interno'};}
  function selecionarExemplar(e,projectId,kit){const itens=[...(e&&e.acervoUsuario||[]),...(e&&e.arquivos||[])].filter(a=>(!projectId||a.projectId===projectId)&&String(a.conteudo||'').length>300&&(a.soberano||a.classe==='produto'||a.validacao&&a.validacao.pronto));const a=itens.find(x=>x.kit===kit)||itens[0];return a?{id:a.id,nome:a.nome,trecho:String(a.conteudo).slice(0,1400)}:null;}
  function perfil(op){const kit=String(op&&op.kit||''),estruturada=op&&op.estruturada;if(estruturada)return{temperature:0.1,top_p:0.8,frequency_penalty:0,seed:68};if(kit==='texto')return{temperature:0.62,top_p:0.92,frequency_penalty:0.12};if(['codigo','pagina','dados','financeiro','laboratorio'].includes(kit))return{temperature:0.2,top_p:0.82,frequency_penalty:0};return{temperature:0.45,top_p:0.9,frequency_penalty:0.05};}
  function repeticaoNgram(texto,n=5){const w=String(texto||'').toLowerCase().match(/[\p{L}\p{N}]+/gu)||[],m=new Map();for(let i=0;i<=w.length-n;i++){const k=w.slice(i,i+n).join(' ');m.set(k,(m.get(k)||0)+1);}return[...m.entries()].filter(([,q])=>q>=3).sort((a,b)=>b[1]-a[1]).slice(0,8);}
  function validar(texto,spec){texto=String(texto||'');spec=spec||{};const total=palavras(texto),notas=[],cliches=CLICHES.reduce((n,rx)=>{rx.lastIndex=0;return n+(texto.match(rx)||[]).length;},0),tokens=texto.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[],diversidade=new Set(tokens).size/Math.max(1,tokens.length),ngrams=repeticaoNgram(texto);if(spec.minPalavras&&total<spec.minPalavras)notas.push(`faltam ${spec.minPalavras-total} palavras para o contrato`);if(spec.maxPalavras&&total>spec.maxPalavras)notas.push(`excede o máximo em ${total-spec.maxPalavras} palavras`);for(const b of spec.batidas||[])if(!texto.toLowerCase().includes(String(b).toLowerCase()))notas.push(`critério ausente: ${b}`);if(total>350&&cliches/total*1000>3)notas.push('densidade de clichês acima do gate');if(total>500&&diversidade<0.22)notas.push('diversidade lexical baixa');if(ngrams.length)notas.push('blocos de linguagem repetidos');return{pronto:notas.length===0,notas:notas.slice(0,12),metricas:{palavras:total,cliches,clichesPorMil:total?cliches/total*1000:0,diversidadeLexical:diversidade,ngramsRepetidos:ngrams.length}};}
  const ferramentas=[
    {type:'function',function:{name:'ler_artefato',description:'Lê um artefato real pelo id, somente leitura.',parameters:{type:'object',properties:{id:{type:'string'},inicio:{type:'integer'},fim:{type:'integer'}},required:['id']}}},
    {type:'function',function:{name:'buscar_canon',description:'Busca um termo no acervo e artefatos do projeto.',parameters:{type:'object',properties:{termo:{type:'string'}},required:['termo']}}},
    {type:'function',function:{name:'contar_palavras',description:'Conta palavras de um texto fornecido.',parameters:{type:'object',properties:{texto:{type:'string'}},required:['texto']}}}
  ];
  function executarFerramenta(nome,args,ctx){args=args||{};const e=ctx&&ctx.empresa||(S.state&&S.state.atual&&S.state.atual());if(nome==='contar_palavras')return{palavras:palavras(args.texto)};if(nome==='ler_artefato'){const a=e&&[...(e.arquivos||[]),...(e.acervoUsuario||[])].find(x=>x.id===args.id);if(!a)return{erro:'artefato inexistente'};const ls=String(a.conteudo||'').split(/\r?\n/),ini=Math.max(1,Number(args.inicio)||1),fim=Math.min(ls.length,Number(args.fim)||ini+120);return{id:a.id,nome:a.nome,inicio:ini,fim,conteudo:ls.slice(ini-1,fim).join('\n')};}if(nome==='buscar_canon'){const termo=String(args.termo||'').toLowerCase();return[...(e&&e.arquivos||[]),...(e&&e.acervoUsuario||[])].filter(a=>String(a.conteudo||'').toLowerCase().includes(termo)).slice(0,8).map(a=>({id:a.id,nome:a.nome}));}return{erro:'ferramenta não autorizada'};}
  function preparar(op,ctx){const e=ctx&&ctx.empresa||(S.state&&S.state.atual&&S.state.atual()),spec=compilarSpec(op,ctx),exemplar=selecionarExemplar(e,op&&op.projectId,op&&op.kit),amostra=exemplar?`\nEXEMPLAR APROVADO (${exemplar.nome}) — imite densidade e precisão, não o conteúdo:\n${exemplar.trecho}`:'';return{spec,exemplar,perfil:perfil(op),prompt:`ESPECIFICAÇÃO EXECUTÁVEL:\n${JSON.stringify(spec)}${amostra}`,tools:ferramentas,executar:(n,a)=>executarFerramenta(n,a,{empresa:e})};}
  async function melhorDeN(gerar,avaliar,n=2){const xs=[];for(let i=0;i<Math.max(1,Math.min(3,n));i++){try{const valor=await gerar(i);xs.push({valor,nota:Number(await avaliar(valor))||0,indice:i});}catch(erro){xs.push({valor:null,nota:-Infinity,indice:i,erro});}}const ordenados=xs.sort((a,b)=>b.nota-a.nota);if(!ordenados[0]||ordenados[0].valor==null)throw(ordenados.find(x=>x.erro)||{}).erro||new Error('Nenhum candidato pôde ser gerado.');return ordenados[0];}
  S.buff={compilarSpec,selecionarExemplar,perfil,validar,preparar,ferramentas,executarFerramenta,melhorDeN,FUNDACAO_SCHEMA,formatoFundacao,extrairJSON,validarFundacao};
})(window.S);
