/* Camada operacional v66: custo por resultado, event log, replay e ferramentas locais. */
(function(S){
  'use strict';
  const enc=v=>JSON.stringify(v,(k,x)=>k.startsWith('_')?undefined:x);
  function hash(v){let h=2166136261,s=typeof v==='string'?v:enc(v);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
  function palavras(v){return (String(v||'').trim().match(/\S+/g)||[]).length;}
  function linhas(v){return String(v||'').split(/\r?\n/).length;}
  function diff(a,b){a=String(a||'');b=String(b||'');if(a===b)return{igual:true,mudanca:0,adicionados:0,removidos:0};const aa=a.split(/\r?\n/),bb=b.split(/\r?\n/),sa=new Set(aa),sb=new Set(bb),ad=bb.filter(x=>!sa.has(x)).length,rm=aa.filter(x=>!sb.has(x)).length;return{igual:false,mudanca:Math.min(1,(ad+rm)/Math.max(1,aa.length+bb.length)),adicionados:ad,removidos:rm};}
  function taskType(op){const t=`${op&&op.tipo||''} ${op&&op.motivo||''} ${op&&op.etapa||''}`.toLowerCase();if(/funda/.test(t))return'fundacao';if(/revis|candidato|final/.test(t))return'revisao';if(/conteudo|produ/.test(t))return'producao';if(/reuni|colabor/.test(t))return'colaboracao';if(/financ/.test(t))return'financeiro';return'deliberacao';}
  function taskKey(op){return `${taskType(op)}|${String(op&&op.kit||'geral')}`;}
  function event(tipo,dados,empresa){const e=empresa||(S.state&&S.state.atual&&S.state.atual());if(!e)return null;e.eventos=Array.isArray(e.eventos)?e.eventos:[];const ev={id:'ev_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7),seq:Number(e.eventSeq||0)+1,em:Date.now(),tipo:String(tipo),dados:dados||{}};e.eventSeq=ev.seq;e.eventos.push(ev);if(e.eventos.length>12000)e.eventos.splice(0,e.eventos.length-12000);if(S.persistencia)void S.persistencia.salvarEvento(e.id,ev);S.bus.emit('evento',ev);return ev;}
  function contrato(d){d=d||{};const c=Object.assign({arquivosEsperados:[],secoesObrigatorias:[],minPalavras:0,maxPalavras:0,referenciasDevemResolver:true,schema:null,cliente:Boolean(d.clienteVisivel)},d.contratoAceitacao||{});if(c.cliente){c.semMetatexto=true;c.empacotamento=true;}return c;}
  function validarContrato(c,arquivos){c=c||{};arquivos=Array.isArray(arquivos)?arquivos:[];const notas=[],nomes=arquivos.map(a=>String(a.nome||''));for(const n of c.arquivosEsperados||[])if(!nomes.some(x=>x===n||x.endsWith('/'+n)))notas.push('arquivo obrigatório ausente: '+n);const unido=arquivos.map(a=>String(a.conteudo||'')).join('\n');for(const s of c.secoesObrigatorias||[])if(!unido.toLowerCase().includes(String(s).toLowerCase()))notas.push('seção obrigatória ausente: '+s);const p=palavras(unido);if(c.minPalavras&&p<c.minPalavras)notas.push(`extensão abaixo do contrato: ${p}/${c.minPalavras} palavras`);if(c.maxPalavras&&p>c.maxPalavras)notas.push(`extensão acima do contrato: ${p}/${c.maxPalavras} palavras`);return{pronto:notas.length===0,criteriosTotal:(c.arquivosEsperados||[]).length+(c.secoesObrigatorias||[]).length+Boolean(c.minPalavras)+Boolean(c.maxPalavras),notas,metricas:{palavras:p,arquivos:arquivos.length}};}
  function defaultBudget(t){const base={visual:2500,pagina:7000,codigo:7000,texto:8000,laboratorio:3500,financeiro:2000,comercial:3500,dados:3500,autonomo:5000};return{saidaMax:base[t&&t.kit]||5000,contextoMax:9000,chamadasMax:t&&t.clienteVisivel?6:3,saidaUsada:0,entradaUsada:0,chamadasUsadas:0,status:'ativo'};}
  function normalizeBudget(b,t){b=b&&typeof b==='object'?b:defaultBudget(t);if(b.saidaMax==null)b.saidaMax=Number(b.tokensMax)||defaultBudget(t).saidaMax;if(b.contextoMax==null)b.contextoMax=9000;if(b.saidaUsada==null)b.saidaUsada=Number(b.tokensUsados)||0;if(b.entradaUsada==null)b.entradaUsada=0;if(b.chamadasUsadas==null)b.chamadasUsadas=0;if(!b.chamadasMax)b.chamadasMax=t&&t.clienteVisivel?6:3;delete b.tokensMax;delete b.tokensUsados;return b;}
  function taskFor(op){const e=S.state&&S.state.atual&&S.state.atual();return e&&op&&op.taskId&&(e.tarefas||[]).find(x=>x.id===op.taskId);}
  function authorize(op,estimate){const t=taskFor(op);if(!t)return true;const b=t.orcamentoTokens=normalizeBudget(t.orcamentoTokens,t),est=typeof estimate==='number'?{entrada:0,saida:Number(estimate)||0}:Object.assign({entrada:0,saida:0},estimate||{});if(est.entrada>b.contextoMax){const er=new Error(`Contexto de ${est.entrada} tokens excede o teto de ${b.contextoMax}. O montador deve comprimir.`);er.contextoExcedido=true;er.contextoMax=b.contextoMax;throw er;}if(b.status==='escalado'||b.chamadasUsadas>=b.chamadasMax||b.saidaUsada+est.saida>b.saidaMax){b.status='escalado';t.status='aguardando_decisao';t.para=null;t.escaladaEm=Date.now();t.motivoEscalada=`Orçamento de saída atingido: ${b.saidaUsada}/${b.saidaMax} tokens, ${b.chamadasUsadas}/${b.chamadasMax} chamadas.`;event('tarefa.orcamento_escalado',{taskId:t.id,orcamento:b});const er=new Error(t.motivoEscalada+' A gerente deve mudar abordagem, orçamento ou responsável.');er.limiteLocal=true;er.orcamentoTarefa=true;throw er;}return true;}
  function observeCall(r){const e=S.state&&S.state.atual&&S.state.atual();if(!e||!r)return;if(r.taskId){const t=(e.tarefas||[]).find(x=>x.id===r.taskId);if(t){const b=t.orcamentoTokens=normalizeBudget(t.orcamentoTokens,t);b.saidaUsada+=Number(r.saida||0);b.entradaUsada+=Number(r.entrada||0);b.chamadasUsadas+=1;}}e.roteamentoEvidencia=e.roteamentoEvidencia||{};const k=`${taskKey(r)}|${r.modelo||'?'}`,x=e.roteamentoEvidencia[k]||(e.roteamentoEvidencia[k]={modelo:r.modelo,tipo:taskType(r),kit:r.kit||'geral',chamadas:0,sucessosTecnicos:0,aprovacoes:0,avaliacoes:0,custo:0,tokens:0});x.chamadas++;x.sucessosTecnicos+=r.ok?1:0;x.custo+=Number(r.custo||0);x.tokens+=Number(r.tokens||0);event(r.ok?'ia.chamada_concluida':'ia.chamada_falhou',{callId:r.id,taskId:r.taskId||null,modelo:r.modelo,custo:r.custo,tokens:r.tokens,codigo:r.codigo||null});}
  function approve(taskId,model,approved,details){const e=S.state&&S.state.atual&&S.state.atual();if(!e)return;const t=(e.tarefas||[]).find(x=>x.id===taskId),k=`${taskKey(t||{})}|${model||'?'}`,x=e.roteamentoEvidencia&&e.roteamentoEvidencia[k];if(x){x.avaliacoes=Number(x.avaliacoes||0)+1;x.aprovacoes=Number(x.aprovacoes||0)+(approved?1:0);x.ultimaEvidencia=details||null;}}
  function deterministicEvidence(taskId,model,checks){checks=checks||{};const vals=Object.values(checks).filter(v=>typeof v==='boolean');if(!vals.length)return;approve(taskId,model,vals.every(Boolean),checks);}
  function choose(op,models,fallback){const e=S.state&&S.state.atual&&S.state.atual(),ev=e&&e.roteamentoEvidencia||{},prefix=`${taskKey(op)}|`,candidatos=[models.leve,models.padrao,models.avancado].filter((x,i,a)=>x&&a.indexOf(x)===i).map(model=>{const x=ev[prefix+model]||{},n=Number(x.avaliacoes||0),ap=Number(x.aprovacoes||0),taxa=n?ap/n:0,custo=Number(x.custo||0)/Math.max(1,Number(x.chamadas||0));return{model,n,taxa,custo};});const elegiveis=candidatos.filter(x=>x.n>=3&&x.taxa>=0.72).sort((a,b)=>a.custo-b.custo);return elegiveis[0]?{modelo:elegiveis[0].model,motivo:`evidência de qualidade: ${(elegiveis[0].taxa*100).toFixed(0)}% de aprovação com menor custo`,aprendeu:true}:fallback;}
  function sellable(files){files=Array.isArray(files)?files:[];const names=files.map(x=>String(x.nome||'').toLowerCase()),notes=[];if(files.length>1&&!names.some(x=>/(^|\/)readme(?:\.md|\.txt)?$/.test(x)))notes.push('README ausente');if(files.some(x=>/\.(?:js|css|html)$/.test(String(x.nome||'').toLowerCase()))&&!names.some(x=>/(^|\/)index\.html$/.test(x)))notes.push('prévia index.html ausente');const all=files.map(x=>String(x.conteudo||'')).join('\n');if(/\b(?:TODO|FIXME|lorem ipsum|nota interna|pendente de revis[aã]o)\b/i.test(all))notes.push('metatexto ou placeholder interno');if(!files.length)notes.push('pacote vazio');return{vendavel:notes.length===0,notas:notes,arquivos:files.length};}
  function applyPatch(source,patch){source=String(source||'');patch=String(patch||'');const range=patch.match(/^SUBSTITUIR_LINHAS:\s*(\d+)\s*-\s*(\d+)\s*\n---\s*\n([\s\S]*)$/m);if(range){const lines=source.split(/\r?\n/),from=Number(range[1]),to=Number(range[2]);if(from<1||to<from||to>lines.length)throw new Error(`Intervalo ${from}-${to} fora do arquivo de ${lines.length} linhas.`);return lines.slice(0,from-1).concat(range[3].replace(/\n$/,'').split(/\r?\n/),lines.slice(to)).join('\n');}if(/^BUSCAR:\s*/m.test(patch)){const m=patch.match(/BUSCAR:\s*\n([\s\S]*?)\nSUBSTITUIR:\s*\n([\s\S]*)/);if(!m||!source.includes(m[1]))throw new Error('Trecho BUSCAR não encontrado ou patch inválido.');return source.replace(m[1],m[2]);}const ls=patch.split(/\r?\n/),out=source.split(/\r?\n/),h=ls.findIndex(x=>/^@@/.test(x));if(h<0)throw new Error('Patch sem SUBSTITUIR_LINHAS ou hunk @@.');const mm=ls[h].match(/@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/);if(!mm)throw new Error('Cabeçalho de diff inválido.');let at=Number(mm[1])-1,res=out.slice(0,at),i=at;for(const l of ls.slice(h+1)){if(l[0]===' '){if(out[i]!==l.slice(1))throw new Error('Contexto do patch não confere.');res.push(out[i++]);}else if(l[0]==='-'){if(out[i]!==l.slice(1))throw new Error('Linha removida não confere.');i++;}else if(l[0]==='+')res.push(l.slice(1));else if(l[0]==='\\')continue;}return res.concat(out.slice(i)).join('\n');}
  const FORMAS={serial:{exige:['índice ou sumário','todas as unidades presentes','numeração contínua'],proibe:['unidade vazia','placeholder']},pacote:{exige:['ponto de entrada','links internos resolvem','README'],proibe:['referência a arquivo inexistente']},acervo:{exige:['manifesto de itens','nenhum item duplicado']},iterada:{exige:['versão supera a anterior por diff material']},servico:{exige:['entrada original preservada','saída corresponde a cada entrada']}};
  function validateForm(form,files,ctx){form=String(form||'iterada').toLowerCase();files=Array.isArray(files)?files:[];ctx=ctx||{};const notes=[],all=files.map(x=>String(x.conteudo||'')).join('\n'),names=files.map(x=>String(x.nome||'').toLowerCase());if(form==='serial'){const nums=[...all.matchAll(/(?:cap[ií]tulo|aula|epis[oó]dio|unidade)\s+(\d+)/gi)].map(m=>Number(m[1]));if(!nums.length)notes.push('obra serial sem unidades numeradas');else{const uniq=[...new Set(nums)].sort((a,b)=>a-b);if(uniq[0]!==1||uniq.some((n,i)=>n!==i+1))notes.push('numeração serial descontínua');}if(/\b(?:TODO|placeholder|a preencher)\b/i.test(all))notes.push('unidade com placeholder');}else if(form==='pacote'){const s=sellable(files);notes.push(...s.notas);}else if(form==='acervo'){if(files.length<2)notes.push('acervo sem múltiplos itens');if(new Set(names).size!==names.length)notes.push('itens duplicados');if(!names.some(n=>/manifest|indice|índice/.test(n)))notes.push('manifesto de itens ausente');}else if(form==='iterada'&&ctx.anterior!=null&&diff(ctx.anterior,all).mudanca<0.008)notes.push('versão sem diff material');else if(form==='servico'){if(ctx.entradas&&ctx.entradas.length&&!ctx.entradas.every(v=>all.includes(String(v))))notes.push('entrada original não preservada ou sem saída correspondente');}return{forma:FORMAS[form]?form:'iterada',pronto:notes.length===0,notas:notes,regras:FORMAS[form]||FORMAS.iterada};}
  function citedIds(content){return [...new Set(String(content||'').match(/\b(?:func|task|tarefa|artefato|arq|f|a|t)_[a-z0-9_-]+\b/gi)||[])];}
  function validateReality(content,e){const notes=[],known=new Set([...(e&&e.equipe||[]),...(e&&e.tarefas||[]),...(e&&e.arquivos||[])].map(x=>String(x.id)));const unknown=citedIds(content).filter(id=>!known.has(id));if(unknown.length)notes.push('entidades inexistentes citadas: '+unknown.slice(0,8).join(', '));const declared=[...String(content||'').matchAll(/(\d+)\s+(?:desenvolvedores?|designers?|redatores?|analistas?)/gi)].map(m=>Number(m[1]));if(declared.some(n=>n>(e&&e.equipe||[]).filter(x=>x.papel==='func').length))notes.push('quadro declarado maior que a equipe real');return{pronto:notes.length===0,notas:notes};}
  function anchorTerms(items){const stop=new Set('sobre entre para como uma com que dos das por seu sua seus suas este esta isso mais não sem'.split(' '));const freq={};for(const item of items||[]){const text=String(item&&item.conteudo||'');for(const m of text.matchAll(/\b[A-ZÁÉÍÓÚÂÊÔÃÕÇ][\p{L}\d'-]{3,}(?:\s+[A-ZÁÉÍÓÚÂÊÔÃÕÇ][\p{L}\d'-]{2,})*/gu)){const term=m[0].trim();if(!stop.has(term.toLowerCase()))freq[term]=(freq[term]||0)+1;}}return Object.keys(freq).sort((a,b)=>freq[b]-freq[a]).slice(0,40);}
  function validateAnchoring(content,items){const terms=anchorTerms(items);if(!terms.length)return{pronto:true,termos:[],encontrados:[]};const found=terms.filter(t=>String(content||'').toLowerCase().includes(t.toLowerCase()));return{pronto:found.length>0,termos:terms,encontrados:found,notas:found.length?[]:['nenhum elemento concreto do acervo soberano foi utilizado']};}
  function project(events){const p={tarefas:{},produtos:{},custoUSD:0,tokens:0,ultimoSeq:0};for(const e of events||[]){p.ultimoSeq=Math.max(p.ultimoSeq,Number(e.seq)||0);if(e.tipo==='tarefa.criada')p.tarefas[e.dados.taskId]={status:'aberta',...e.dados};if(e.tipo==='tarefa.nao_progresso_escalado'||e.tipo==='tarefa.orcamento_escalado'){p.tarefas[e.dados.taskId]=Object.assign(p.tarefas[e.dados.taskId]||{},{status:'aguardando_decisao'});}if(e.tipo==='produto.liberado')p.produtos[e.dados.produtoId]=e.dados;if(e.tipo==='ia.chamada_concluida'){p.custoUSD+=Number(e.dados.custo||0);p.tokens+=Number(e.dados.tokens||0);}}return p;}
  function lint(a){const tipo=String(a.tipo||'').toLowerCase(),c=String(a.conteudo||''),erros=[];try{if(tipo==='json'||tipo==='webmanifest')JSON.parse(c);if(tipo==='jsonl')c.split(/\r?\n/).filter(Boolean).forEach(JSON.parse);if(tipo==='js'&&!/^\s*(?:import|export)\b/m.test(c))new Function(c);}catch(e){erros.push(e.message);}if(tipo==='html'&&!/<html|<!doctype/i.test(c))erros.push('documento HTML sem raiz');if(['js','ts','jsx','tsx'].includes(tipo)){const abre=(c.match(/[({[]/g)||[]).length,fecha=(c.match(/[)}\]]/g)||[]).length;if(abre!==fecha)erros.push('delimitadores possivelmente desequilibrados');}return{valido:erros.length===0,erros};}
  function checkReferences(files){files=Array.isArray(files)?files:[];const names=new Set(files.map(f=>String(f.nome||'').replace(/^\.\//,'').replace(/^\//,''))),missing=[];for(const f of files){const c=String(f.conteudo||''),rx=/(?:src|href)\s*=\s*['"]([^'"]+)['"]|url\(\s*['"]?([^)'"\s]+)|!?\[[^\]]*\]\(([^)\s]+)/gi;let m;while((m=rx.exec(c))){const ref=String(m[1]||m[2]||m[3]||'').split(/[?#]/)[0].replace(/^\.\//,'').replace(/^\//,'');if(ref&&!/^(?:https?:|data:|mailto:|tel:|javascript:|#)/i.test(ref)&&!names.has(ref)&&![...names].some(n=>n.endsWith('/'+ref)||n.split('/').pop()===ref.split('/').pop()))missing.push(`${f.nome}: ${ref}`);}}return{valido:missing.length===0,ausentes:[...new Set(missing)]};}
  S.operacao={hash,diff,event,evento:event,projetar:project,contrato,validarContrato,orcamentoPadrao:defaultBudget,normalizarOrcamento:normalizeBudget,autorizarChamada:authorize,registrarChamada:observeCall,registrarAprovacao:approve,registrarEvidenciaDeterministica:deterministicEvidence,escolherModelo:choose,vendavel:sellable,formas:FORMAS,validarForma:validateForm,validarRealidade:validateReality,validarAncoragem:validateAnchoring};
  S.toolkit={aplicarPatch:applyPatch,diff,lint,metricas:a=>({caracteres:String(a.conteudo||'').length,palavras:palavras(a.conteudo),linhas:linhas(a.conteudo),hash:hash(a.conteudo)}),buscar:(itens,termo)=>(itens||[]).filter(x=>String(x.conteudo||'').toLowerCase().includes(String(termo||'').toLowerCase())).map(x=>({id:x.id,nome:x.nome})),referencias:checkReferences,unir:arquivos=>S.arquivo.zip(arquivos||[]),vendavel:sellable};

  const idb=typeof indexedDB!=='undefined';let dbp=null;
  function db(){if(!idb)return Promise.resolve(null);if(dbp)return dbp;dbp=new Promise((resolve,reject)=>{const q=indexedDB.open('agents-enterprise-v66',1);q.onupgradeneeded=()=>{const d=q.result;['snapshots','events','traces'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'});});};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});return dbp;}
  async function put(store,value){const d=await db();if(!d)return false;return new Promise((resolve,reject)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error);});}
  function compact(dbv){const x=JSON.parse(enc(dbv));x.compactado=true;for(const e of x.estudios||[]){for(const a of e.arquivos||[])if(String(a.conteudo||'').length>48000){a.conteudoRef=`${e.id}:${a.id}:${hash(a.conteudo)}`;a.conteudo='[conteúdo preservado no IndexedDB]';}for(const a of e.acervoUsuario||[])if(String(a.conteudo||'').length>48000){a.conteudoRef=`${e.id}:${a.id}:${hash(a.conteudo)}`;a.conteudo='[conteúdo preservado no IndexedDB]';}e.eventos=(e.eventos||[]).slice(-250);e.iaChamadas=(e.iaChamadas||[]).slice(-250);e.log=(e.log||[]).slice(-500);}return x;}
  async function save(dbv){if(!idb)return false;const copia=JSON.parse(enc(dbv));await put('snapshots',{id:'latest',em:Number(copia.persistidoEm)||Date.now(),data:copia});return true;}
  async function hydrate(target){const d=await db();if(!d)return false;const row=await new Promise((resolve,reject)=>{const q=d.transaction('snapshots').objectStore('snapshots').get('latest');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});if(!row||!row.data||(!target.compactado&&Number(row.em)<=Number(target.persistidoEm||0)))return false;target.estudios=(row.data.estudios||[]).map(S.state.normalizarEstudio).filter(Boolean);target.atual=row.data.atual||target.estudios[0]?.id||null;target.acervoUsuario=row.data.acervoUsuario||[];target.persistidoEm=Number(row.em)||0;target.compactado=false;S.bus.emit('trocou');S.bus.emit('storage-hidratado');return true;}
  S.persistencia={disponivel:idb,gravar:save,hidratar:hydrate,projecaoLocal:compact,salvarEvento:(empresaId,ev)=>put('events',{id:`${empresaId}:${String(ev.seq).padStart(12,'0')}`,empresaId,...ev})};
  S.replay={
    gravar:r=>put('traces',{id:r.id||'trace_'+Date.now(),em:Date.now(),registro:JSON.parse(enc(r))}),
    provedor:traces=>{let i=0;return{chamar:async()=>{if(i>=traces.length)throw new Error('Replay sem trace correspondente.');const t=traces[i++];if(t.erro)throw Object.assign(new Error(t.erro),{transitoria:t.transitoria});return{texto:t.saida||t.texto||'',usage:t.detalhesUso||{},modelo:t.modelo,custo:t.custo||0,ms:t.ms||0};},restantes:()=>traces.length-i,consumidos:()=>i};},
    executar:async(traces,cenario)=>{const provedor=S.replay.provedor(Array.isArray(traces)?traces:[]),inicio=Date.now();const resultado=await cenario(provedor);return{resultado,consumidos:provedor.consumidos(),restantes:provedor.restantes(),custoUSD:(traces||[]).slice(0,provedor.consumidos()).reduce((n,t)=>n+Number(t.custo||0),0),duracaoMs:Date.now()-inicio};}
  };
})(window.S);
