/* Camada operacional v66: custo por resultado, event log, replay e ferramentas locais. */
(function(S){
  'use strict';
  const enc=v=>JSON.stringify(v,(k,x)=>k.startsWith('_')?undefined:x);
  function hash(v){let h=2166136261,s=typeof v==='string'?v:enc(v);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
  function palavras(v){return (String(v||'').trim().match(/\S+/g)||[]).length;}
  function linhas(v){return String(v||'').split(/\r?\n/).length;}
  function diff(a,b){a=String(a||'');b=String(b||'');if(a===b)return{igual:true,mudanca:0,adicionados:0,removidos:0};const aa=a.split(/\r?\n/),bb=b.split(/\r?\n/),sa=new Set(aa),sb=new Set(bb),ad=bb.filter(x=>!sa.has(x)).length,rm=aa.filter(x=>!sb.has(x)).length;return{igual:false,mudanca:Math.min(1,(ad+rm)/Math.max(1,aa.length+bb.length)),adicionados:ad,removidos:rm};}
  function taskType(op){const t=`${op&&op.tipo||''} ${op&&op.motivo||''} ${op&&op.etapa||''}`.toLowerCase();if(/funda/.test(t))return'fundacao';if(/revis|candidato|final/.test(t))return'revisao';if(/conteudo|produ/.test(t))return'producao';if(/reuni|colabor/.test(t))return'colaboracao';if(/financ/.test(t))return'financeiro';return'deliberacao';}
  function event(tipo,dados,empresa){const e=empresa||(S.state&&S.state.atual&&S.state.atual());if(!e)return null;e.eventos=Array.isArray(e.eventos)?e.eventos:[];const ev={id:'ev_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7),seq:Number(e.eventSeq||0)+1,em:Date.now(),tipo:String(tipo),dados:dados||{}};e.eventSeq=ev.seq;e.eventos.push(ev);if(e.eventos.length>12000)e.eventos.splice(0,e.eventos.length-12000);if(S.persistencia)void S.persistencia.salvarEvento(e.id,ev);S.bus.emit('evento',ev);return ev;}
  function contrato(d){d=d||{};const c=Object.assign({arquivosEsperados:[],secoesObrigatorias:[],minPalavras:0,maxPalavras:0,referenciasDevemResolver:true,schema:null,cliente:Boolean(d.clienteVisivel)},d.contratoAceitacao||{});if(c.cliente){c.semMetatexto=true;c.empacotamento=true;}return c;}
  function validarContrato(c,arquivos){c=c||{};arquivos=Array.isArray(arquivos)?arquivos:[];const notas=[],nomes=arquivos.map(a=>String(a.nome||''));for(const n of c.arquivosEsperados||[])if(!nomes.some(x=>x===n||x.endsWith('/'+n)))notas.push('arquivo obrigatório ausente: '+n);const unido=arquivos.map(a=>String(a.conteudo||'')).join('\n');for(const s of c.secoesObrigatorias||[])if(!unido.toLowerCase().includes(String(s).toLowerCase()))notas.push('seção obrigatória ausente: '+s);const p=palavras(unido);if(c.minPalavras&&p<c.minPalavras)notas.push(`extensão abaixo do contrato: ${p}/${c.minPalavras} palavras`);if(c.maxPalavras&&p>c.maxPalavras)notas.push(`extensão acima do contrato: ${p}/${c.maxPalavras} palavras`);return{pronto:notas.length===0,criteriosTotal:(c.arquivosEsperados||[]).length+(c.secoesObrigatorias||[]).length+Boolean(c.minPalavras)+Boolean(c.maxPalavras),notas,metricas:{palavras:p,arquivos:arquivos.length}};}
  function defaultBudget(t){const base={visual:6000,pagina:18000,codigo:16000,texto:16000,laboratorio:9000,financeiro:5000,comercial:9000,dados:9000,autonomo:12000};return{tokensMax:base[t.kit]||12000,chamadasMax:t.clienteVisivel?6:4,tokensUsados:0,chamadasUsadas:0,status:'ativo'};}
  function authorize(op,estimativa){const e=S.state&&S.state.atual&&S.state.atual(),t=e&&op&&op.taskId&&(e.tarefas||[]).find(x=>x.id===op.taskId);if(!t)return true;t.orcamentoTokens=t.orcamentoTokens||defaultBudget(t);const b=t.orcamentoTokens;if(b.status==='escalado'||b.chamadasUsadas>=b.chamadasMax||b.tokensUsados+Number(estimativa||0)>b.tokensMax){b.status='escalado';t.status='aguardando_decisao';t.motivoEscalada=`Orçamento da tarefa atingido: ${b.tokensUsados}/${b.tokensMax} tokens, ${b.chamadasUsadas}/${b.chamadasMax} chamadas.`;event('tarefa.orcamento_escalado',{taskId:t.id,orcamento:b});const er=new Error(t.motivoEscalada+' A gerente deve mudar abordagem, orçamento ou responsável.');er.limiteLocal=true;er.orcamentoTarefa=true;throw er;}return true;}
  function observeCall(r){const e=S.state&&S.state.atual&&S.state.atual();if(!e||!r)return;if(r.taskId){const t=(e.tarefas||[]).find(x=>x.id===r.taskId);if(t){t.orcamentoTokens=t.orcamentoTokens||defaultBudget(t);t.orcamentoTokens.tokensUsados+=Number(r.tokens||0);t.orcamentoTokens.chamadasUsadas+=1;}}e.roteamentoEvidencia=e.roteamentoEvidencia||{};const k=`${taskType(r)}|${r.modelo||'?'}`,x=e.roteamentoEvidencia[k]||(e.roteamentoEvidencia[k]={modelo:r.modelo,tipo:taskType(r),chamadas:0,sucessos:0,aprovacoes:0,custo:0,tokens:0});x.chamadas++;x.sucessos+=r.ok?1:0;x.custo+=Number(r.custo||0);x.tokens+=Number(r.tokens||0);event(r.ok?'ia.chamada_concluida':'ia.chamada_falhou',{callId:r.id,taskId:r.taskId||null,modelo:r.modelo,custo:r.custo,tokens:r.tokens,codigo:r.codigo||null});}
  function approve(taskId,model,approved){const e=S.state&&S.state.atual&&S.state.atual();if(!e)return;const t=(e.tarefas||[]).find(x=>x.id===taskId),k=`${taskType(t||{})}|${model||'?'}`,x=e.roteamentoEvidencia&&e.roteamentoEvidencia[k];if(x){x.avaliacoes=Number(x.avaliacoes||0)+1;x.aprovacoes+=approved?1:0;}}
  function choose(op,models,fallback){const e=S.state&&S.state.atual&&S.state.atual(),ev=e&&e.roteamentoEvidencia||{},tipo=taskType(op),candidatos=[models.leve,models.padrao,models.avancado].filter((x,i,a)=>x&&a.indexOf(x)===i).map(model=>{const x=ev[`${tipo}|${model}`]||{},n=Number(x.avaliacoes||x.chamadas||0),ap=Number(x.aprovacoes||x.sucessos||0),taxa=n?ap/n:0,custo=Number(x.custo||0)/Math.max(1,Number(x.chamadas||0));return{model,n,taxa,custo};});const elegiveis=candidatos.filter(x=>x.n>=3&&x.taxa>=0.72).sort((a,b)=>a.custo-b.custo);return elegiveis[0]?{modelo:elegiveis[0].model,motivo:`evidência: ${(elegiveis[0].taxa*100).toFixed(0)}% aprovação com menor custo`,aprendeu:true}:fallback;}
  function sellable(files){files=Array.isArray(files)?files:[];const names=files.map(x=>String(x.nome||'').toLowerCase()),notes=[];if(files.length>1&&!names.some(x=>/(^|\/)readme(?:\.md|\.txt)?$/.test(x)))notes.push('README ausente');if(files.some(x=>/\.(?:js|css|html)$/.test(String(x.nome||'').toLowerCase()))&&!names.some(x=>/(^|\/)index\.html$/.test(x)))notes.push('prévia index.html ausente');const all=files.map(x=>String(x.conteudo||'')).join('\n');if(/\b(?:TODO|FIXME|lorem ipsum|nota interna|pendente de revis[aã]o)\b/i.test(all))notes.push('metatexto ou placeholder interno');if(!files.length)notes.push('pacote vazio');return{vendavel:notes.length===0,notas:notes,arquivos:files.length};}
  function applyPatch(source,patch){source=String(source||'');patch=String(patch||'');if(/^BUSCAR:\s*/m.test(patch)){const m=patch.match(/BUSCAR:\s*\n([\s\S]*?)\nSUBSTITUIR:\s*\n([\s\S]*)/);if(!m||!source.includes(m[1]))throw new Error('Trecho BUSCAR não encontrado ou patch inválido.');return source.replace(m[1],m[2]);}const ls=patch.split(/\r?\n/),out=source.split(/\r?\n/),h=ls.findIndex(x=>/^@@/.test(x));if(h<0)throw new Error('Diff unificado sem hunk @@.');const mm=ls[h].match(/@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/);if(!mm)throw new Error('Cabeçalho de diff inválido.');let at=Number(mm[1])-1,res=out.slice(0,at),i=at;for(const l of ls.slice(h+1)){if(l[0]===' '){if(out[i]!==l.slice(1))throw new Error('Contexto do patch não confere.');res.push(out[i++]);}else if(l[0]==='-'){if(out[i]!==l.slice(1))throw new Error('Linha removida não confere.');i++;}else if(l[0]==='+')res.push(l.slice(1));else if(l[0]==='\\')continue;}return res.concat(out.slice(i)).join('\n');}
  function project(events){const p={tarefas:{},produtos:{},custoUSD:0,tokens:0,ultimoSeq:0};for(const e of events||[]){p.ultimoSeq=Math.max(p.ultimoSeq,Number(e.seq)||0);if(e.tipo==='tarefa.criada')p.tarefas[e.dados.taskId]={status:'aberta',...e.dados};if(e.tipo==='tarefa.nao_progresso_escalado'||e.tipo==='tarefa.orcamento_escalado'){p.tarefas[e.dados.taskId]=Object.assign(p.tarefas[e.dados.taskId]||{},{status:'aguardando_decisao'});}if(e.tipo==='produto.liberado')p.produtos[e.dados.produtoId]=e.dados;if(e.tipo==='ia.chamada_concluida'){p.custoUSD+=Number(e.dados.custo||0);p.tokens+=Number(e.dados.tokens||0);}}return p;}
  function lint(a){const tipo=String(a.tipo||'').toLowerCase(),c=String(a.conteudo||''),erros=[];try{if(tipo==='json'||tipo==='webmanifest')JSON.parse(c);if(tipo==='jsonl')c.split(/\r?\n/).filter(Boolean).forEach(JSON.parse);}catch(e){erros.push(e.message);}if(tipo==='html'&&!/<html|<!doctype/i.test(c))erros.push('documento HTML sem raiz');if(['js','ts','jsx','tsx'].includes(tipo)){const abre=(c.match(/[({[]/g)||[]).length,fecha=(c.match(/[)}\]]/g)||[]).length;if(abre!==fecha)erros.push('delimitadores possivelmente desequilibrados');}return{valido:erros.length===0,erros};}
  S.operacao={hash,diff,event,evento:event,projetar:project,contrato,validarContrato,orcamentoPadrao:defaultBudget,autorizarChamada:authorize,registrarChamada:observeCall,registrarAprovacao:approve,escolherModelo:choose,vendavel:sellable};
  S.toolkit={aplicarPatch:applyPatch,diff,lint,metricas:a=>({caracteres:String(a.conteudo||'').length,palavras:palavras(a.conteudo),linhas:linhas(a.conteudo),hash:hash(a.conteudo)}),buscar:(itens,termo)=>(itens||[]).filter(x=>String(x.conteudo||'').toLowerCase().includes(String(termo||'').toLowerCase())).map(x=>({id:x.id,nome:x.nome})),vendavel:sellable};

  const idb=typeof indexedDB!=='undefined';let dbp=null;
  function db(){if(!idb)return Promise.resolve(null);if(dbp)return dbp;dbp=new Promise((resolve,reject)=>{const q=indexedDB.open('agents-enterprise-v66',1);q.onupgradeneeded=()=>{const d=q.result;['snapshots','events','traces'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'});});};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});return dbp;}
  async function put(store,value){const d=await db();if(!d)return false;return new Promise((resolve,reject)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error);});}
  function compact(dbv){const x=JSON.parse(enc(dbv));x.compactado=true;for(const e of x.estudios||[]){for(const a of e.arquivos||[])if(String(a.conteudo||'').length>48000){a.conteudoRef=`${e.id}:${a.id}:${hash(a.conteudo)}`;a.conteudo='[conteúdo preservado no IndexedDB]';}for(const a of e.acervoUsuario||[])if(String(a.conteudo||'').length>48000){a.conteudoRef=`${e.id}:${a.id}:${hash(a.conteudo)}`;a.conteudo='[conteúdo preservado no IndexedDB]';}e.eventos=(e.eventos||[]).slice(-250);e.iaChamadas=(e.iaChamadas||[]).slice(-250);e.log=(e.log||[]).slice(-500);}return x;}
  async function save(dbv){if(!idb)return false;const copia=JSON.parse(enc(dbv));await put('snapshots',{id:'latest',em:Number(copia.persistidoEm)||Date.now(),data:copia});return true;}
  async function hydrate(target){const d=await db();if(!d)return false;const row=await new Promise((resolve,reject)=>{const q=d.transaction('snapshots').objectStore('snapshots').get('latest');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});if(!row||!row.data||(!target.compactado&&Number(row.em)<=Number(target.persistidoEm||0)))return false;target.estudios=(row.data.estudios||[]).map(S.state.normalizarEstudio).filter(Boolean);target.atual=row.data.atual||target.estudios[0]?.id||null;target.acervoUsuario=row.data.acervoUsuario||[];target.persistidoEm=Number(row.em)||0;target.compactado=false;S.bus.emit('trocou');S.bus.emit('storage-hidratado');return true;}
  S.persistencia={disponivel:idb,gravar:save,hidratar:hydrate,projecaoLocal:compact,salvarEvento:(empresaId,ev)=>put('events',{id:`${empresaId}:${String(ev.seq).padStart(12,'0')}`,empresaId,...ev})};
  S.replay={gravar:r=>put('traces',{id:r.id||'trace_'+Date.now(),em:Date.now(),registro:JSON.parse(enc(r))}),provedor:traces=>{let i=0;return{chamar:async()=>{if(i>=traces.length)throw new Error('Replay sem trace correspondente.');const t=traces[i++];if(t.erro)throw Object.assign(new Error(t.erro),{transitoria:t.transitoria});return{texto:t.saida||t.texto||'',usage:t.detalhesUso||{},modelo:t.modelo,custo:t.custo||0,ms:t.ms||0};},restantes:()=>traces.length-i};}};
})(window.S);
